Repository COS301-SE-2024/Culinary-Companion, pull requests merged in 2024-06, with the labels that each got.

#42 Improved design of Profile page to look like initial design
  assets/food10.jpg
  assets/food11.jpg
  assets/food8.jpg
  assets/food9.jpg
  assets/pfp.jpg
  lib/screens/profile_screen.dart
  pubspec.yaml
Labels: frontend

#39 Improved the design of the Recipe Form
  lib/screens/add_recipe_screen.dart
  lib/screens/home_screen.dart
Labels: frontend

#67 Improved styling for landing and log in pages
  assets/Darkmode.png
  assets/Lightmode.png
  assets/google.png
  assets/logo.png
  lib/main.dart
  lib/screens/add_recipe_screen.dart
  lib/screens/landing_screen.dart
  lib/screens/login_screen.dart
  lib/screens/profile_screen.dart
  pubspec.yaml
Labels: enhancement, frontend

#88 Added all the input fields for the confirm details page
  assets/default_profile.jpeg
  lib/main.dart
  lib/screens/add_recipe_screen.dart
  lib/screens/confirm_details.dart
  lib/screens/login_screen.dart
  lib/screens/signup_screen.dart
  pubspec.yaml
Labels: frontend

#89 Seperated some of the functions so the file is not as large and also …
  lib/screens/main.dart
  lib/screens/shopping_pantry_screen.dart
  lib/widgets/confirm_dialog.dart
Labels: frontend

#91 Added padding to the side of the screen and also improved design
  lib/screens/shopping_pantry_screen.dart
Labels: frontend

#115 Added the input field for user to add appliances
  lib/screens/add_recipe_screen.dart
Labels: frontend

#124 Improved design of edit profile page
  lib/screens/edit_profile_screen.dart
Labels: frontend

#116 Recipe popup with some styling
  lib/screens/home_screen.dart
  lib/screens/saved_recipes_screen.dart
  lib/widgets/recipe_card.dart
Labels: frontend

#146 Write unit testing for landing page, login and signup
  .github/workflows/fluuter_ci.yaml
  analysis_options.yaml
  coverage/lcov.info
  lib/screens/landing_screen.dart
  lib/screens/login_screen.dart
  lib/screens/signup_screen.dart
  pubspec.lock
  pubspec.yaml
  test/landing_screen_test.dart
  test/login_screen_test.dart
  test/mock_navigator_observer.dart
  test/mock_navigator_observer.mocks.dart
  test/signup_screen_test.dart
  test/signup_screen_test.mocks.dart
Labels: testing

#157 Changed the Ingredients field in Add recipe to a dropdown
  lib/screens/add_recipe_screen.dart
Labels: frontend

#156 Made sure spice level starts at 1
  lib/screens/add_recipe_screen.dart
Labels: frontend

#155 Made the Pantry page styling same as the Appliance page styling the same.
  lib/screens/pantry_screen.dart
  lib/screens/shopping_list_screen.dart
Labels: frontend

#154 Made the Shopping list styling same as the Appliance page styling.
  lib/screens/shopping_list_screen.dart
Labels: frontend

#153 Added recipe cards widget to the profile page
  lib/screens/profile_screen.dart
Labels: frontend

#165 Worked on Help Menu
  analysis_options.yaml
  assets/helper_chef.png
  lib/screens/add_recipe_screen.dart
  lib/screens/appliances_screen.dart
  lib/screens/confirm_details.dart
  lib/screens/home_screen.dart
  lib/screens/pantry_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/saved_recipes_screen.dart
  lib/screens/shopping_list_screen.dart
  lib/widgets/help_add_recipe.dart
  lib/widgets/help_appliance.dart
  lib/widgets/help_home.dart
  lib/widgets/help_menu.dart
  lib/widgets/help_pantry.dart
  lib/widgets/help_profile.dart
  lib/widgets/help_saved.dart
  lib/widgets/help_shopping.dart
  pubspec.lock
  pubspec.yaml
Labels: frontend

#166 Scalable navbar
  lib/screens/main.dart
  lib/widgets/navbar.dart
Labels: frontend

#173 Finalizing Light theme
  assets/logo_1.png
  lib/main.dart
  lib/screens/add_recipe_screen.dart
  lib/screens/appliances_screen.dart
  lib/screens/confirm_details.dart
  lib/screens/home_screen.dart
  lib/screens/landing_screen.dart
  lib/screens/login_screen.dart
  lib/screens/main.dart
  lib/screens/pantry_screen.dart
  lib/screens/profile_screen.dart
  lib/screens/saved_recipes_screen.dart
  lib/screens/shopping_list_screen.dart
  lib/screens/signup_screen.dart
  lib/widgets/help_add_recipe.dart
  lib/widgets/help_appliance.dart
  lib/widgets/help_home.dart
  lib/widgets/help_menu.dart
  lib/widgets/help_pantry.dart
  lib/widgets/help_profile.dart
  lib/widgets/help_saved.dart
  lib/widgets/help_shopping.dart
  lib/widgets/navbar.dart
  lib/widgets/recipe_card.dart
  pubspec.yaml
Labels: frontend

#180 Fixed the color of the headers for the light mode
  lib/screens/edit_profile_screen.dart
  lib/screens/login_screen.dart
  lib/screens/signup_screen.dart
Labels: bug, frontend
