Repository COS301-SE-2024/Culinary-Companion, pull requests merged in 2024-08, with the labels that each got.

#300 Designed and created a search page to search and filter
  lib/screens/main.dart
  lib/screens/search_screen.dart
  lib/widgets/navbar.dart
Labels: frontend

#307 Fixing scalability issues & Substitutions
  lib/widgets/paste_recipe_screen.dart
  lib/widgets/recipe_card.dart
  lib/widgets/scan_recipe_screen.dart
Labels: frontend

#318 Adjusted some styling of the website
  assets/Darkermode.png
  assets/Darkmode.png
  assets/MobileDarkMode.png
  assets/MobileLightMode.png
  assets/appliances.png
  assets/pantry.png
  assets/recipes.png
  assets/savour.png
  assets/shopping.png
  assets/welcome.png
  lib/screens/confirm_details.dart
  lib/screens/home_screen.dart
  lib/screens/landing_screen.dart
  lib/screens/login_screen.dart
  lib/screens/signup_screen.dart
  lib/screens/tutorial_pages.dart
  lib/widgets/pantry_screen.dart
  lib/widgets/recipe_card.dart
  lib/widgets/shopping_list_screen.dart
  pubspec.yaml
Labels: bug, frontend

#326 Styling before Demo 3
  .vscode/launch.json
  lib/screens/add_recipe_screen.dart
  lib/screens/home_screen.dart
  lib/widgets/chat_widget.dart
  lib/widgets/navbar.dart
  lib/widgets/recipe_card.dart
Labels: frontend

#325 Added light mode to the tutorial page
  assets/Lappliances.png
  assets/Lpantry.png
  assets/Lrecipes.png
  assets/Lsavour.png
  assets/Lshopping.png
  assets/Lwelcome.png
  lib/screens/tutorial_pages.dart
  lib/widgets/desktop_tutorial.dart
  lib/widgets/mobile_tutorial.dart
  lib/widgets/shopping_list_screen.dart
Labels: enhancement, frontend

#327 Changed the Revert button's styling
  lib/widgets/recipe_card.dart
Labels: enhancement, frontend

#250 Modified profile page's styling
  lib/screens/edit_profile_screen.dart
  lib/screens/profile_screen.dart
Labels: frontend

#346 Added the scan and paste recipe screens and fixed button sizes
  lib/screens/add_recipe_screen.dart
  lib/widgets/paste_recipe_screen.dart
  lib/widgets/scan_recipe_screen.dart
Labels: frontend

#360 Added photo button to pantry and permissions for mobile view
  lib/widgets/pantry_screen.dart
  lib/widgets/theme_utils.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: frontend

#362 Added a button so user can adjust recipe to their preferences
  lib/widgets/recipe_card.dart
Labels: frontend
